# Generated by Django 5.2.7 on 2026-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
